variables:
  DEPENDENCIES: gettext gettext-devel gcc redhat-rpm-config automake libtool autoconf autoconf-archive git
                gtk3-devel yelp-tools

build_fedora_33:
  image: fedora:33
  before_script:
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - ./autogen.sh
    - make -j
