variables:
  DEPENDENCIES: gettext gettext-devel gcc git libadwaita-devel gtk4-devel yelp-tools

build_fedora:
  image: fedora:latest
  before_script:
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson build/
    - ninja -C build/
